name: Github CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Build
    name: Build Docker Image
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Check System & Docker 
      uses: actions/checkout@v1
      run: |
        uname -a
        sudo apt-get remove docker docker-engine docker.io containerd runc
        sudo apt update
        sudo apt-get install \
         apt-transport-https \
         ca-certificates \
         curl \
         gnupg-agent \
         software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Build 
      uses: actions/checkout@v1
      env: 
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
      run: /bin/bash push.sh
    