name: Github CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Build
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    # This step uses the hello-world-action stored in this workflow's repository.
    - uses: .
    # This step prints the time.
    - run: /bin/bash push.sh
    