name: Github CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Build
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      env: 
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - run: /bin/bash push.sh
    